force_cast: warning

line_length:
  warning: 200
  error: 500

file_length:
  warning: 600
  error: 1000

opt_in_rules:
  - force_unwrapping
  - legacy_constant
  - legacy_constructor
  - private_action
  - private_outlet
