name: Android Master Build
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - shell: bash
        env:
          clientId: ${{secrets.clientId}}
          clientAuthenticationUrl: ${{secrets.clientAuthenticationUrl}}
          useTwitchAuthentication: ${{secrets.useTwitchAuthentication}}
          debugKeyAlias: ${{secrets.debugKeyAlias}}
          debugKeyPassword: ${{secrets.debugKeyPassword}}
          debugStoreFileName: ${{secrets.debugStoreFileName}}
          debugStorePassword: ${{secrets.debugStorePassword}}
        run: touch local.properties & echo clientId="$clientId" >> local.properties & echo clientAuthenticationUrl="$clientAuthenticationUrl" >> local.properties & echo useTwitchAuthentication="$useTwitchAuthentication" >> local.properties & echo debugKeyAlias="$debugKeyAlias" >> local.properties & echo debugKeyPassword="$debugKeyPassword" >> local.properties & echo debugStoreFileName="$debugStoreFileName" >> local.properties & echo debugStorePassword="$debugStorePassword" >> local.properties
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build the Android App with Gradle
        run: ./gradlew :app:assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Upload to AppCenter
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: abhishek101/Scout-Master-Snapshot
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: Testers
          file: app/build/outputs/apk/debug/app-debug.apk
          notifyTesters: false
          debug: true