name: Android Release Build
on:
  push:
    branches: [ release/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - shell: bash
        env:
          clientId: ${{secrets.clientId}}
          clientAuthenticationUrl: ${{secrets.clientAuthenticationUrl}}
          useTwitchAuthentication: ${{secrets.useTwitchAuthentication}}
          debugKeyAlias: ${{secrets.releaseKeyAlias}}
          debugKeyPassword: ${{secrets.releasePassword}}
          debugStoreFileName: ${{secrets.releaseStoreFileName}}
          debugStorePassword: ${{secrets.releaseStorePassword}}
        run: touch local.properties & echo clientId="$clientId" >> local.properties & echo clientAuthenticationUrl="$clientAuthenticationUrl" >> local.properties & echo useTwitchAuthentication="$useTwitchAuthentication" >> local.properties & echo releaseKeyAlias="$releaseKeyAlias" >> local.properties & echo releaseKeyPassword="$releaseKeyPassword" >> local.properties & echo releaseStoreFileName="$releaseStoreFileName" >> local.properties & echo releaseStorePassword="$releaseStorePassword" >> local.properties
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build the Android App with Gradle
        run: ./gradlew :app:assembleRelease --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/release/app-release.apk
      - name: Upload to AppCenter
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: abhishek101/Scout-Release
          token: ${{secrets.releaseAppCenterToken}}
          group: Testers
          file: app/build/outputs/apk/debug/app-debug.apk
          notifyTesters: false
          debug: false