name: iOS Master Build
on: 
  pull_request:
  push:
    branches:
      - master

jobs:
  build: # make sure build/ci work properly
    runs-on: macOS-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: "Building iOS"
      run: "cd iOS/Scout && xcodebuild -allowProvisioningUpdates -workspace Scout.xcworkspace -scheme Scout SYMROOT=$(PWD)/build"